### ISSUE TITLE
Runner commands

### ISSUE THREAD

**Issue by karencfv** [elastic/ecctl#154]
## Description
In addition to https://github.com/elastic/ecctl/issues/148 the following commands need to be implemented:

-  [x] `runner show` "get-runner" (**GET** /platform/infrastructure/runners/{runner_id})
- [x] `runner resync` "resync-runner" (**POST** /platform/infrastructure/runners/{runner_id}/_resync)
- [x] `runner resync --all` "resync-runners" (**POST** /platform/infrastructure/runners/_resync)
- [x] `runner search` "search-runners" (**POST** /platform/infrastructure/runners/_search)
