### ISSUE TITLE
[Meta] ecctl ESS public api support

### ISSUE THREAD

**Issue by Kushmaro** [elastic/ecctl#161]
To introduce ecctl with support of ESS Public API when It's GA, we'd like to do the following:

- [x] Default to ESS API URL in init flow #159, resolved by #173)

- [x] For ESS, suggest API key auth only #157 

- [x] Handle regions in config when ESS is configured #162 

- [x] Hide platform commands help when configured to ESS  #160 

- [x] Change Docs to state support of ESS https://github.com/elastic/ecctl/pull/267

- [x] Move away from `/clusters` to `/deployment` based endpoints #196

- [x] Remove commented deployment-templates link on `deployment create` command. (To be done once ms36 is live in order to not break the docs build) https://github.com/elastic/ecctl/pull/271

- [x] Revert `ecctl init` command (https://github.com/elastic/ecctl/pull/207) to include other types of infra in the workflow. https://github.com/elastic/ecctl/pull/268

- [x] Create changelog/release notes for ecctl 1.0.0-beta3 https://github.com/elastic/ecctl/pull/273

**Comment by ppapapetrou76** [comment]
@Kushmaro so we need to discuss about those requests. We can't deliver a different version of `ecctl` for ECE vs ESS users

Why ECE users should get the default ESS API url in init flow? 
How `ecctl` can understand that the target env is ESS or ECE

For me we should treat all envs the same. There should be one `ecctl` version that can work on any kind of ESS/ECE environment

**Comment by Kushmaro** [comment]
@ppapapetrou76 definitely didn't want us to maintain two versions of ecctl.
this is really about UX, and some sensible defaults

> Why ECE users should get the default ESS API url in init flow?

Prior to Beta1 we had exactly that, is anything different now?

**Comment by zanbel** [comment]
There is one more bullet I think we should add and will affect other bullets as well. When designing how ecctl will work against ECE and ESS we need to keep in mind there are private environments we should take into account and, while they might be a deployed across a single region at the moment this might change in the future so will be good to have that use case in mind.

**Comment by marclop** [comment]
I'm reopening this issue and adding some more items to be completed

**Comment by karencfv** [comment]
I added a couple of items as well. @Kushmaro, I'm assuming we should change docs and init workflow to include ESS once ECE2.5 is out?

**Comment by Kushmaro** [comment]
@karencfv ECE 2.5 was released yesterday, 
we'd want to include ESS when the Public ESS API goes GA

@zanbel , do we have a hard date for that yet?

**Comment by zanbel** [comment]
MS36 is definitely underway, but since MS actual go live dates are still a moving target and the time it take to release ecctl is far more predictable, I think if we have the relevant PR(s) ready to go and release ecctl when we are really close to complete the release. I would even say we can wait to MS36 to be completed if ecctl release is a matter of clicking a button or can be completed in 1 - 2 days.

WDYT?

**Comment by karencfv** [comment]
Thanks @Kushmaro and @zanbel ! I'll open up some PRs for the missing items, and we'll stay tuned for the go live dates. An ecctl release is pretty quick :)
