### ISSUE TITLE
[Meta] Add commands for AppSearch deployments

### ISSUE THREAD

**Issue by karencfv** [elastic/ecctl#166]
## Description
`ecctl` should have basic CRUD commands for AppSearch.

At the moment there are no AppSearch specific API endpoints, so the deployment API should be used.

Commands to be implemented:
- [x] `ecctl deployment appsearch show`
- [x] `ecctl deployment appsearch create`
- [x] `ecctl deployment appsearch upgrade`
- [x] `ecctl deployment appsearch shutdown`
- [x] `ecctl deployment appsearch delete`
