### ISSUE TITLE
Modify ES, Kibana and APM commands to use deployments API endpoints

### ISSUE THREAD

**Issue by karencfv** [elastic/ecctl#196]
## Description
With the upcoming deprecation of the  /clusters/{elasticsearch|kibana|apm} API endpoints, We need to refactor the ES, Kibana and APM packages to use the new deployments API endpoints.

We also need to come to an agreement on the following:

- We keep the the user facing commands the same and only change the underlying packages to point to the deployments API endpoints. This would be the option with minimal user facing impact.
- We remove all relevant `ecctl deployment elasticsearch|kibana|apm` commands, and switch people over to use `ecctl deployment show|create|delete --type <apm|elasticsearch|kibana>`. This might make more sense technically, but would have a large user facing impact.

Once we have come up with a way forward we can keep this issue as a meta and create individual issues for each task.

Commands and subcommands to remove entirely since there is an equal from the deployments api:

- [x] deployment apm https://github.com/elastic/ecctl/pull/241
- [x] deployment appsearch https://github.com/elastic/ecctl/pull/243
- [x] deployment kibana https://github.com/elastic/ecctl/pull/248
- [x] deployment elasticsearch https://github.com/elastic/ecctl/pull/251

Additional related tasks:

- [x] Remove all "cluster" related code and utility functions #258

Tagging @Kushmaro and @zanbel here as well for any input from the PM side

**Comment by Kushmaro** [comment]
Thanks for opening this @karencfv.
I'm +1 on option 2, since our main object of operation as per our API, is now deployments, rather 'individual clusters'. as before.

Since we're still in beta, although there will be some user impact (especially once ESS APIs are GA)
I think it's the preferred user experience and we would still be able to perform such changes prior to GA.

As we've talked over slack, the use case of cross-managing specific instance types using 'deployment kibana' commands (for example), seems like more of an SRE use case rather an ESS / ECE customer use case, where one 'herds' kibana instances, rather than petting a specific deployment.

**Comment by zanbel** [comment]
What @Kushmaro said. We manage deployments, not sure what are those clusters you speak of 😉

**Comment by karencfv** [comment]
Sounds good! We'll move forward in this direction then. I'll be opening up related issues shortly

**Comment by marclop** [comment]
I'm grabbing the APM side of things for the moment

**Comment by karencfv** [comment]
I'm grabbing Appsearch :)

**Comment by karencfv** [comment]
I'm grabbing elasticsearch next

**Comment by marclop** [comment]
That's a big one, I'll take Kibana next and give you a hand if you need some help with the elasticsearch command

**Comment by karencfv** [comment]
sounds good, thank you!

**Comment by marclop** [comment]
It seems like we've removed all the commands from ecctl. I think we can close this.

**Comment by karencfv** [comment]
I updated the description. 

I think we need to at least remove all the `ClusterParams` stuff as well 🤔 I can work on that
