### ISSUE TITLE
Move necessary packages to cloud-sdk-go

### ISSUE THREAD

**Issue by karencfv** [elastic/ecctl#275]
## Description
In order to have other projects make use of the certain packages and its subpackages that currently live in ecctl, it makes sense to move them cloud-sdk-go. This is somewhat of a large chunk of work so I'll add some bullet points here to have this issue as a meta.

#### Deployment packages (https://github.com/elastic/ecctl/pull/285)
- [x] deployment/apm
- [x] deployment/depresource
- [x] deployment/deputil
- [x] deployment/kibana
- [x] deployment/note
- [x] deployment/planutil
- [x] deployment/

#### Platform packages

- [x] Move all platform packages to the `cloud-sdk-go`
- [x] Remove all platform packages from this project

#### User packages

- [ ] Move all user packages to the `cloud-sdk-go`
- [ ] Remove all user packages from this project

### Functions

- [x] Moved UserLogin from `ecctl` over to `cloud-sdk-go` elastic/cloud-sdk-go#101

### Testing niceties

- [x] Moved the creation of mock errors to the `api/mock` package. In particular, it contains both the assertion error and `Sample<StatusText>()` functions: `SampleInternalError` `SampleNotFound`, `SampleBadRequest`, the equivalent multi errors are `multierror<StatusText>` variables.

**Comment by marclop** [comment]
I'm kind of indirectly already working on this since I was testing the changes made by #101 by "faking" the `sdk` in `ecctl`. I think since I'm already doing those changes I'll move the packages over to `cloud-sdk-go`.

**Comment by karencfv** [comment]
@marclop can you add the packages that you're removing to the checklist on the issue's descritption? 🙏

**Comment by karencfv** [comment]
Reopening since we haven't removed all the packages from ecctl yet :)

**Comment by karencfv** [comment]
I'll take the task of removing the deployment apis from ecctl :)
