### ISSUE TITLE
ecctl GA

### ISSUE THREAD

**Issue by karencfv** [elastic/ecctl#335]
## Description
ecctl will be GA soon 🎉 This is a list to track the tasks we need to finish.

### Done

- [x] Move all APIs from ecctl to cloud-sdk-go https://github.com/elastic/ecctl/issues/275
- [x] Refactor platform APIs to require `Region` parameter https://github.com/elastic/cloud-sdk-go/issues/129
- [x] Change `ecctl platform stack` command and subcommands to `ecctl stack` for parity with the API https://github.com/elastic/ecctl/pull/329
- [x] Ability for deployment template APIs to use the `deployment` format. https://github.com/elastic/cloud-sdk-go/issues/159 https://github.com/elastic/ecctl/pull/332
- [x] Update client/models to MS39 and update `user update` API https://github.com/elastic/cloud-sdk-go/issues/160
- [x] Update client/models to MS41 https://github.com/elastic/cloud-sdk-go/pull/167 @karencfv 
- [x] Flag based deployment create https://github.com/elastic/ecctl/issues/334 @karencfv #341 (The PR has been merged but the issue about deployment template ID availability needs to be solved) 
  - [x] Resource Get @karencfv https://github.com/elastic/cloud-sdk-go/pull/170
- [x] Add custom ecctl headers (https://github.com/elastic/ecctl/issues/333) @marclop
- [x] Make sure Enterprise Search is supported in all commands it should be.
  - [x] Vacate
  - [x] flag-based Deployment create https://github.com/elastic/ecctl/pull/341 https://github.com/elastic/cloud-sdk-go/pull/168 
  - [x] Various mentions of resourcekinds @karencfv https://github.com/elastic/ecctl/pull/342 https://github.com/elastic/cloud-sdk-go/pull/170
- [x] Use deployment templates new APIs instead of the old platform API ones. Also replace old `platform deployment-template` command and subcommands or mark them as deprecated @marclop elastic/cloud-sdk-go#171 and #343.
- [x] Make sure our documentation in ecctl and cloud-sdk-go is up to date with recent changes @karencfv https://github.com/elastic/ecctl/pull/347
- [x] Add `--generate-update-payload` to `ecctl deployment show` command (#355 and elastic/cloud-sdk-go#181)
- [x] Move the `deptemplateapi.Get` API calls to `deptemplateapi.List` with the instance filter for `depresource.NewPayload` (cloud-sdk-go). @marclop (elastic/cloud-sdk-go#178) (#348)
- [x] Change topology element "name" to "node_type" (elastic/cloud-sdk-go#181 and #356) @karencfv 
- [x] Unify `ecctl deployment create` size unit types to gb (#357) @karencfv 
~- [ ] Flag based deployment update https://github.com/elastic/ecctl/issues/225~
- [x] Write up the GA changelog @karencfv https://github.com/elastic/ecctl/pull/350

**Comment by karencfv** [comment]
@marclop @Kushmaro please feel free to add anything you think I might be missing here :)

**Comment by karencfv** [comment]
cc @nrichers

**Comment by karencfv** [comment]
Heads up 👉 https://github.com/elastic/cloud/issues/62498

**Comment by karencfv** [comment]
All items completed 🎉  ecctl release issue -> https://github.com/elastic/ecctl/issues/349
