### ISSUE TITLE
Road to GA & Onwards

### ISSUE THREAD

**Issue by ppapapetrou76** [elastic/ecctl#41]
_This meta-issue lists several activities that we’ll need to complete before announcing ecctl as a generally available tool from elastic, which will be later on turned to respective GH issues once the team reaches a consensus._

# Prior to GA To-Dos
## Must-have feature/fixes (by priority)

- [x] Moving to deployments API instead of cluster APIs
  - [x] Elasticsearch Create (https://github.com/elastic/ecctl/issues/62)
  - [x] Kibana Create (https://github.com/elastic/ecctl/pull/71)
  - [x] APM Create (#79)
- [x] Remove “enabling” Kibana / APM & component commands, with the move to the deployment API
  - [x] Remove "kibana enable" command (https://github.com/elastic/ecctl/pull/71)
  - [x] Remove "apm enable" command (#79)
- [x] Remove any ESS related references:( https://github.com/elastic/ecctl/issues/43 ) 
- [x] Remove plural aliases, use only “<obj> list” as convention ( https://github.com/elastic/ecctl/issues/42 )
- [x] Enhance ‘version’ command with the following (https://github.com/elastic/ecctl/issues/37)
- [x] **[META]**: Implement Deployment Resource APIs(#83)

## Bugs to be fixed

- [x] init flow command fails (non-zero command code) although output notes success if `$HOME/.ecctl directory doesn’t exist` ( https://github.com/elastic/ecctl/issues/46 ) 
- [x] Running the init command with changes to config file doesn’t seem to actually change the conf file ( https://github.com/elastic/ecctl/issues/45 )
- [x] Change cli help texts to reflect mandatory and non-mandatory flags ( https://github.com/elastic/ecctl/issues/44 )
- [x] Fix broken deployment show commands (https://github.com/elastic/ecctl/issues/56)

**Comment by marclop** [comment]
We. can close this
