### ISSUE TITLE
Add CRUD commands for deployment resources

### ISSUE THREAD

**Issue by marclop** [elastic/ecctl#83]
## Description
Now that the swagger spec in cloud-sdk-go has been [updated](https://github.com/elastic/cloud-sdk-go/pull/9) to the latest changes in 2.4 we need to implement the new CRUD endpoints for the deployments api that relate to resources with the following IDs:

- [x] cancel-deployment-resource-pending-plan (@marclop, elastic/ecctl#72)
- [x] delete-deployment-stateless-resource (@marclop, #88)
- [x] upgrade-deployment-stateless-resource (@marclop, https://github.com/elastic/ecctl/pull/76)
- [x] get-deployment-apm-resource-info (@karencfv, https://github.com/elastic/ecctl/pull/14)
- [x] get-deployment-es-resource-info (@karencfv, https://github.com/elastic/ecctl/pull/14)
- [x] get-deployment-kib-resource-info (@karencfv, https://github.com/elastic/ecctl/pull/14)
- [x] set-deployment-resource-raw-metadata (@karencfv )
- [x] restore-deployment-resource (@marclop, #87)
- [x] shutdown-deployment-es-resource (@marclop, #86)
- [x] shutdown-deployment-stateless-resource (@marclop, #86)
- [x] start-deployment-resource-instances (@karencfv https://github.com/elastic/ecctl/pull/89)
- [x] start-deployment-resource-instances-all (@karencfv https://github.com/elastic/ecctl/pull/89)
- [x] start-deployment-resource-instances-all-maintenance-mode (@karencfv #89 )
- [x] start-deployment-resource-maintenance-mode (@karencfv #89 )
- [x] stop-deployment-resource-instances (@karencfv, #81)
- [x] stop-deployment-resource-instances-all (@karencfv, #81)
- [x] stop-deployment-resource-instances-all-maintenance-mode (@karencfv, #81)
- [x] stop-deployment-resource-maintenance-mode (@karencfv, #81)

**Comment by marclop** [comment]
I'm currently working on the implementation of a command which calls `shutdown-deployment-es-resource` or `shutdown-deployment-stateless-resource` depending on which resource type has been set for shutdown.

**Comment by karencfv** [comment]
working on ` start-deployment-resource-instances-` related commands :)

**Comment by karencfv** [comment]
working on `set-deployment-resource-raw-metadata`

**Comment by marclop** [comment]
Work has been complete, thanks @karencfv !!
