### ISSUE TITLE
Smoke test commands

### ISSUE THREAD

**Issue by karencfv** [elastic/ecctl#99]
## Description
Commands should be smoke tested against an ECE environment before the next release.

List to track commands that have been tested:

- [x] auth
    - [x] key create @marclop
    - [x] key delete @marclop
    - [x] key list @marclop
    - [x] key show @marclop
- [x] deployment
    - [x] apm
        - [x] create - Works fine using the simplified flags, but I keep getting an error when trying to use a file definition. Please someone verify that this is an actual error and not something that I might be doing wrong @karencfv, @marclop Fixed in #109
        - [x] delete @karencfv 
        - [x] list @karencfv 
        - [x] plan cancel @karencfv
        - [x] plan history @karencfv
        - [x] plan monitor @karencfv
        - [x] plan reapply @karencfv
        - [x] restart @karencfv
        - [x] resync @karencfv
        - [x] show @karencfv
        - [x] stop @karencfv
        - [x] upgrade @karencfv
    - [x] create @karencfv
    - [x] delete @karencfv
    - [x] elasticsearch
        - [x] console @karencfv 
        - [x] delete @karencfv 
        - [x] diagnose `open diagnostic-d972998ab23145fa99258d883c204f21.zip: no such file or directory` ? Please someone verify that this is an actual error and not something that I might be doing wrong @karencfv @marclop fixed in #110.
        - [x] instances override-capacity @karencfv 
        - [x] instances pause @karencfv 
        - [x] instances resume @karencfv 
        - [x] instances start-routing @karencfv 
        - [x] instances stop-routing @karencfv 
        - [x] keystore set @karencfv 
        - [x] keystore show @karencfv 
        - [x] list @karencfv 
        - [x] monitoring disable @karencfv 
        - [x] monitoring enable @karencfv 
        - [x] plan cancel @karencfv 
        - [x] plan history @karencfv 
        - [x] plan monitor @karencfv 
        - [x] plan reapply @karencfv 
        - [x] plan update @karencfv 
        - [x] reallocate @karencfv 
        - [x] restart @karencfv 
        - [x] resync @karencfv 
        - [x] search @karencfv 
        - [x] show @karencfv 
        - [x] shutdown @karencfv 
        - [x] start @karencfv 
        - [x] upgrade @karencfv 
    - [x] kibana 
        - [x] create Works fine using the simplified flags, but I keep getting an error when trying to use a file definition. Please someone verify that this is an actual error and not something that I might be doing wrong @karencfv, @marclop Fixed in #109
        - [x] delete @karencfv 
        - [x] list @karencfv 
        - [x] plan monitor @karencfv 
        - [x] reallocate @karencfv 
        - [x] restart @karencfv 
        - [x] resync @karencfv 
        - [x] show @karencfv 
        - [x] start @karencfv 
        - [x] stop @karencfv 
        - [x] upgrade @karencfv 
    - [x] list @karencfv 
    - [ ] note (works, but it sends all notes to the ES cluster and when trying to retrieve the note, you can't use any of the deployment IDs returned with ` deployment list`. It's all pretty confusing, tried to fix it but wasn't really able to) @karencfv 
        - [x] create @karencfv 
        - [x] list @karencfv 
        - [x] show @karencfv 
        - [x] update @karencfv 
    - [x] plan cancel @karencfv 
    - [x] resource @karencfv 
        - [x] delete (https://github.com/elastic/ecctl/pull/104) @karencfv 
        - [x] restore @karencfv 
        - [x] shutdown @karencfv 
        - [x] start @karencfv 
        - [x] start-maintenance @karencfv 
        - [x] stop @karencfv 
        - [x] stop-maintenance @karencfv 
        - [x] upgrade @karencfv 
    - [x] restore @karencfv
    - [x] search @karencfv
    - [x] show @karencfv
    - [x] shutdown @karencfv
    - [x] update @karencfv

- [x] generate @karencfv 
    - [x] completions @karencfv 
    - [x] docs @karencfv 
- [x] help @karencfv 
- [x] init @marclop 
- [x] platform
    - [x] allocator @karencfv 
        - [x] list @karencfv 
        - [x] maintenance @karencfv 
        - [x] metadata @karencfv 
        - [x] search @karencfv 
        - [x] show @karencfv 
        - [x] vacate @karencfv 
    - [x] constructor @karencfv 
        - [x] list @karencfv 
        - [x] maintenance @karencfv 
        - [x] show @karencfv 
    - [x] deployment-template @karencfv 
        - [x] create @karencfv 
        - [x] delete @karencfv 
        - [x] list @karencfv 
        - [x] pull @karencfv 
        - [x] show @karencfv 
        - [x] update @karencfv 
    - [x] enrollment-token @karencfv 
        - [x] create @karencfv 
        - [x] delete @karencfv 
        - [x] list @karencfv 
    - [x] info @karencfv 
    - [x] instance-configuration @karencfv 
        - [x] create @karencfv 
        - [x] delete @karencfv 
        - [x] list @karencfv 
        - [x] pull @karencfv 
        - [x] show @karencfv 
        - [x] update @karencfv 
    - [x] proxy @karencfv 
        - [x] filtered-group create @karencfv 
        - [x] filtered-group delete @karencfv 
        - [x] filtered-group list @karencfv 
        - [x] filtered-group show @karencfv 
        - [x] filtered-group update @karencfv 
        - [x] list @karencfv 
        - [x] show @karencfv 
    - [x] repository @karencfv 
        - [x] create @karencfv 
        - [x] delete @karencfv 
        - [x] list @karencfv 
        - [x] show @karencfv 
    - [x] role
        - [x] create @karencfv 
        - [x] delete @karencfv 
        - [x] list @karencfv 
        - [x] show @karencfv 
    - [x] stack
        - [x] delete @marclop
        - [x] list @karencfv 
        - [x] show @karencfv 
        - [x] upload (@marclop, #105)
- [x] user
    - [x] create @karencfv 
    - [x] delete @karencfv 
    - [x] disable @karencfv 
    - [x] enable @karencfv 
    - [x] key
        - [x] delete @marclop
        - [x] list @marclop
        - [x] show @marclop #106
    - [x] list @karencfv 
    - [x] show @karencfv 
    - [x] update @karencfv 
- [x] version @karencfv

**Comment by marclop** [comment]
@karencfv @ppapapetrou76 the deployment note command needs to be reworked, It works, but it does with some quirks. I can work on it on the next milestone and focus on releasing ecctl for the rest of this one.
